name: Build WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-webgl:
    name: Build Unity WebGL
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Unity (version stable v3)
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 6000.0.23f1   # ✅ ta version d’Unity 6.x
          targetPlatform: WebGL
          projectPath: .
          buildsPath: build
          buildName: HookDrive
          versioning: Semantic
          buildMethod: UnityBuilderAction.Builder.BuildProject
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # 3️⃣ Upload du build WebGL
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: HookDrive-WebGL
          path: build/HookDrive
