name: Build WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-webgl:
    name: Build Unity WebGL
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Correction du bug "Cannot find module 'graphql'"
      - name: Fix missing graphql dependency
        run: npm install graphql

      # 3️⃣ Configuration et build Unity
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.23f1  # ✅ Unity 6.x (modifie si besoin)
          targetPlatform: WebGL
          projectPath: .
          buildsPath: build           # ⚠️ remplace buildPath
          buildName: HookDrive         # nom du dossier final : build/HookDrive
          versioning: Semantic
          buildMethod: UnityBuilderAction.Builder.BuildProject
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # 4️⃣ Upload du build final
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: HookDrive-WebGL
          path: build/HookDrive
