name: Build WebGL (Web-poki)

on:
  push:
    branches:
      - main  # ou remplace par ta branche de développement si besoin
  workflow_dispatch:

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cache Unity Library pour accélérer les builds
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-

      # 3. Installer Unity
      - name: Install Unity
        uses: game-ci/unity-install@v3
        with:
          unityVersion: 6000.2.3f1
          targetPlatform: WebGL

      # 4. Build WebGL
      - name: Build WebGL
        uses: game-ci/unity-builder@v3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildName: Web-poki
          buildPath: build
          buildMethod: ""  # tu peux mettre ici le nom d'une fonction statique si tu veux contrôler le build depuis un script C#
          unityVersion: 6000.2.3f1

      # 5. Upload du build en artifact
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/Web-poki
