name: Build WebGL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 6000.2.3f1
          targetPlatform: WebGL
          projectPath: .
          customLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Build Project WebGL
        run: |
          echo "Starting WebGL build..."
          "C:\Program Files\Unity\Hub\Editor\6000.2.3f1\Editor\Unity.exe" ^
            -projectPath "$GITHUB_WORKSPACE" ^
            -buildTarget WebGL ^
            -executeMethod BuildWebGL.Build ^
            -quit ^
            -batchmode ^
            -nographics ^
            -logFile "$GITHUB_WORKSPACE/Builds/build.log"

      - name: Upload WebGL Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build
          path: Builds/WebGL
