name: Build WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-webgl:
    name: Build Unity WebGL
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configuration de la version de Unity
      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.23f1 # ✅ Unity 6.x : adapte si ta version diffère
          targetPlatform: WebGL
          buildName: HookDrive
          buildPath: build/webgl
          versioning: Semantic
          buildMethod: UnityBuilderAction.Builder.BuildProject
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # 3️⃣ Upload du build en artefact
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: HookDrive-WebGL
          path: build/webgl
