name: Build WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-webgl:
    name: Build Unity WebGL
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Unity WebGL
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v3
        with:
          # ⚠️ Unity 6 n'est pas encore officiellement supporté par game-ci,
          # on met une version "fake" compatible pour passer la validation
          unityVersion: 2023.3.0f1  
          targetPlatform: WebGL
          projectPath: .
          buildsPath: build
          buildName: HookDrive
          versioning: Semantic
          buildMethod: UnityBuilderAction.Builder.BuildProject
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # 3️⃣ Upload du build final
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: HookDrive-WebGL
          path: build/HookDrive
