name: Build WebGL (Self-Hosted Runner)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Utilise ton PC
    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build Unity WebGL via ton exe Unity installé
      - name: Build WebGL
        run: |
          "C:\Program Files\Unity\Hub\Editor\6000.2.3f1\Editor\Unity.exe" ^
          -projectPath "%CD%" ^
          -buildTarget WebGL ^
          -executeMethod BuildWebGL.Build ^
          -quit ^
          -batchmode ^
          -nographics
          
      # 3. Zip et upload le build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: Builds/Web-poki
