name: Unity WebGL Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-webgl:
    runs-on: windows-latest

    steps:
      # 1️⃣ Récupérer le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Unity
      - name: Setup Unity Builder
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 6000.2.3f1        # ta version exacte
          targetPlatform: WebGL           # build WebGL
          projectPath: .                  # chemin relatif à la racine du repo
          unityLicense: ${{ secrets.UNITY_LICENSE }} # secret Unity Personal

      # 3️⃣ Optionnel : paramètres personnalisés pour accélérer le build
        # customParameters: -quit -batchmode -nographics

      # 4️⃣ Upload du build
      - name: Upload WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: Build/WebGL
